import base64
import logging

from odoo import models

_logger = logging.getLogger(__name__)


class PosOrder(models.Model):
    _inherit = "pos.order"

    def _validahacienda_pos(self, max_orders=10, no_partner=True):
        """Skip POS XML generation for orders that will be invoiced.

        When a POS order is marked ``to_invoice``, the electronic XML must be
        generated by the accounting invoice flow to avoid duplicate submissions.
        """
        domain = [
            ("state", "in", ("paid", "done", "invoiced")),
            ("to_invoice", "=", True),
            ("tipo_documento", "in", ("TE", "FE", "NC")),
            ("state_tributacion", "=", False),
        ]

        if no_partner:
            domain.append(("partner_id", "=", False))
        else:
            domain.extend([
                ("partner_id", "!=", False),
                ("partner_id.vat", "!=", False),
            ])

        to_invoice_orders = self.search(domain)
        if to_invoice_orders:
            to_invoice_orders.write({"state_tributacion": "no_aplica"})
            _logger.info(
                "E-INV CR - POS XML omitido para %s orden(es) con to_invoice=True: %s",
                len(to_invoice_orders),
                ", ".join(to_invoice_orders.mapped("name")),
            )

        return super()._validahacienda_pos(max_orders=max_orders, no_partner=no_partner)

    def _pos_ticket_pdf_binary_fields(self):
        """Known binary field candidates that can contain a ticket PDF.

        Returns tuples ``(data_field, filename_field_or_false)`` and only keeps
        fields available on the current model to stay compatible across modules.
        """
        self.ensure_one()
        candidates = [
            ("pdf_file", "pdf_filename"),
            ("ticket_pdf", "ticket_pdf_filename"),
            ("comprobante_pdf", "comprobante_pdf_filename"),
        ]
        return [
            (data_field, filename_field)
            for data_field, filename_field in candidates
            if data_field in self._fields
        ]

    def _get_or_create_pos_ticket_pdf_attachment(self):
        """Return an ``ir.attachment`` with the POS ticket PDF for this order.

        The method first reuses existing PDF attachments on ``pos.order`` to
        avoid duplicates. If none exists, it tries well-known binary field
        candidates created by CR electronic invoicing modules and persists them
        as a standard attachment for emailing.
        """
        self.ensure_one()

        attachment_model = self.env["ir.attachment"]
        existing_pdf = attachment_model.search(
            [
                ("res_model", "=", self._name),
                ("res_id", "=", self.id),
                ("mimetype", "=", "application/pdf"),
            ],
            limit=1,
        )
        if existing_pdf:
            return existing_pdf

        for data_field, filename_field in self._pos_ticket_pdf_binary_fields():
            binary_data = self[data_field]
            if not binary_data:
                continue

            filename = self[filename_field] if filename_field and filename_field in self._fields else False
            if not filename:
                filename = f"{self.name or 'POS'}_ticket.pdf"

            if isinstance(binary_data, bytes):
                datas = base64.b64encode(binary_data)
            elif isinstance(binary_data, str):
                try:
                    base64.b64decode(binary_data)
                    datas = binary_data
                except Exception:  # pragma: no cover - defensive branch for legacy field formats
                    datas = base64.b64encode(binary_data.encode())
            else:
                continue

            return attachment_model.create(
                {
                    "name": filename,
                    "type": "binary",
                    "datas": datas,
                    "res_model": self._name,
                    "res_id": self.id,
                    "mimetype": "application/pdf",
                }
            )

        return False
