import logging

from odoo import models

_logger = logging.getLogger(__name__)


class PosOrder(models.Model):
    _inherit = "pos.order"

    def _validahacienda_pos(self, max_orders=10, no_partner=True):
        """Skip POS XML generation for orders that will be invoiced.

        When a POS order is marked ``to_invoice``, the electronic XML must be
        generated by the accounting invoice flow to avoid duplicate submissions.
        """
        domain = [
            ("state", "in", ("paid", "done", "invoiced")),
            ("to_invoice", "=", True),
            ("tipo_documento", "in", ("TE", "FE", "NC")),
            ("state_tributacion", "=", False),
        ]

        if no_partner:
            domain.append(("partner_id", "=", False))
        else:
            domain.extend([
                ("partner_id", "!=", False),
                ("partner_id.vat", "!=", False),
            ])

        to_invoice_orders = self.search(domain)
        if to_invoice_orders:
            to_invoice_orders.write({"state_tributacion": "no_aplica"})
            _logger.info(
                "E-INV CR - POS XML omitido para %s orden(es) con to_invoice=True: %s",
                len(to_invoice_orders),
                ", ".join(to_invoice_orders.mapped("name")),
            )

        return super()._validahacienda_pos(max_orders=max_orders, no_partner=no_partner)
